### ISSUE TITLE
ArrayIndexOutOfBoundsException at TrackListAdapter.updateAt(TrackListFragment.java:1014)

### ISSUE THREAD

**Issue by panovvitalik** [panovvitalik/PhotoTracker#119]
--------- beginning of crash
06-23 06:58:50.774  9516  9516 E AndroidRuntime: FATAL EXCEPTION: main
06-23 06:58:50.774  9516  9516 E AndroidRuntime: Process: vitalypanov.phototracker, PID: 9516
06-23 06:58:50.774  9516  9516 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=109; index=-1
06-23 06:58:50.774  9516  9516 E AndroidRuntime: 	at java.util.ArrayList.set(ArrayList.java:455)
06-23 06:58:50.774  9516  9516 E AndroidRuntime: 	at vitalypanov.phototracker.fragment.TrackListFragment$TrackListAdapter.updateAt(TrackListFragment.java:1014)
06-23 06:58:50.774  9516  9516 E AndroidRuntime: 	at vitalypanov.phototracker.fragment.TrackListFragment$TrackListHolder$7$1$1$1$1$1$1.run(TrackListFragment.java:561)
06-23 06:58:50.774  9516  9516 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:789)
06-23 06:58:50.774  9516  9516 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:98)
06-23 06:58:50.774  9516  9516 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:169)
06-23 06:58:50.774  9516  9516 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6595)
06-23 06:58:50.774  9516  9516 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-23 06:58:50.774  9516  9516 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
06-23 06:58:50.774  9516  9516 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by panovvitalik** [comment]
Fixed
