### ISSUE TITLE
Warning in log: Service leak connection error in log

### ISSUE THREAD

**Issue by panovvitalik** [panovvitalik/PhotoTracker#14]
Activity vitalypanov.phototracker.activity.RunningTrackPagerActivity has leaked ServiceConnection vitalypanov.phototracker.RunningTrackShortInfoFragment$10@db9253 that was originally bound here
                                                                          android.app.ServiceConnectionLeaked: Activity vitalypanov.phototracker.activity.RunningTrackPagerActivity has leaked ServiceConnection vitalypanov.phototracker.RunningTrackShortInfoFragment$10@db9253 that was originally bound here
                                                                              at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1351)
                                                                              at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1246)
                                                                              at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1490)
                                                                              at android.app.ContextImpl.bindService(ContextImpl.java:1462)
                                                                              at android.content.ContextWrapper.bindService(ContextWrapper.java:643)
                                                                              at vitalypanov.phototracker.RunningTrackShortInfoFragment.onStart(RunningTrackShortInfoFragment.java:377)

**Comment by panovvitalik** [comment]
Fixed.
