### ISSUE TITLE
Crash: IllegalStateException: The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged

### ISSUE THREAD

**Issue by panovvitalik** [panovvitalik/PhotoTracker#142]
--------- beginning of crash
07-12 11:50:25.226 23930 23930 E AndroidRuntime: FATAL EXCEPTION: main
07-12 11:50:25.226 23930 23930 E AndroidRuntime: Process: vitalypanov.phototracker, PID: 23930
07-12 11:50:25.226 23930 23930 E AndroidRuntime: java.lang.IllegalStateException: The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! Expected adapter item count: 13, found: 16 Pager id: vitalypanov.phototracker:id/activity_pager_images_view_pager Pager class: class android.support.v4.view.ViewPager Problematic adapter: class vitalypanov.phototracker.activity.TrackImagesPagerActivity$6
07-12 11:50:25.226 23930 23930 E AndroidRuntime: 	at android.support.v4.view.ViewPager.populate(ViewPager.java:1137)
07-12 11:50:25.226 23930 23930 E AndroidRuntime: 	at android.support.v4.view.ViewPager.populate(ViewPager.java:1086)
07-12 11:50:25.226 23930 23930 E AndroidRuntime: 	at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1616)
07-12 11:50:25.226 23930 23930 E AndroidRuntime: 	at android.view.View.measure(View.java:22020)
07-12 11:50:25.226 23930 23930 E AndroidRuntime: 	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
07-12 11:50:25.226 23930 23930 E AndroidRuntime: 	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
07-12 11:50:25.226 23930 23930 E AndroidRuntime: 	at android.view.View.measure(View.java:22020)
07-12 11:50:25.226 23930 23930 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
07-12 11:50:25.226 23930 23930 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
07-12 11:50:25.226 23930 23930 E AndroidRuntime: 	at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:141)
07-12 11:50:25.226 23930 23930 E AndroidRuntime: 	at android.view.View.measure(View.java:22020)
07-12 11:50:25.226 23930 23930 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
07-12 11:50:25.226 23930 23930 E AndroidRuntime: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
07-12 11:50:25.226 23930 23930 E AndroidRuntime: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
07-12 11:50:25.226 23930 23930 E AndroidRuntime: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
07-12 11:50:25.226 23930 23930 E AndroidRuntime: 	at android.view.View.measure(View.java:22020)
07-12 11:50:25.226 23930 23930 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
07-12 11:50:25.226 23930 23930 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
07-12 11:50:25.226 23930 23930 E AndroidRuntime: 	at android.view.View.measure(View.java:22020)
07-12 11:50:25.226 23930 23930 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
07-12 11:50:25.226 23930 23930 E AndroidRuntime: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
07-12 11:50:25.226 23930 23930 E AndroidRuntime: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
07-12 11:50:25.226 23930 23930 E AndroidRuntime: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
07-12 11:50:25.226 23930 23930 E AndroidRuntime: 	at android.view.View.measure(View.java:22020)
07-12 11:50:25.226 23930 23930 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
07-12 11:50:25.226 23930 23930 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
07-12 11:50:25.226 23930 23930 E AndroidRuntime: 	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:727)
07-12 11:50:25.226 23930 23930 E AndroidRuntime: 	at android.view.View.measure(View.java:22020)
07-12 11:50:25.226 23930 23930 E AndroidRuntime: 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2414)
07-12 11:50:25.226 23930 23930 E AndroidRuntime: 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1502)
07-12 11:50:25.226 23930 23930 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1755)
07-12 11:50:25.226 23930 23930 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1390)
07-12 11:50:25.226 23930 23930 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6762)
07-12 11:50:25.226 23930 23930 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
07-12 11:50:25.226 23930 23930 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:778)
07-12 11:50:25.226 23930 23930 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:713)
07-12 11:50:25.226 23930 23930 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
07-12 11:50:25.226 23930 23930 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:789)
07-12 11:50:25.226 23930 23930 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:98)
07-12 11:50:25.226 23930 23930 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:169)
07-12 11:50:25.226 23930 23930 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6595)
07-12 11:50:25.226 23930 23930 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-12 11:50:25.226 23930 23930 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
07-12 11:50:25.226 23930 23930 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by panovvitalik** [comment]
Trying to fix
