### ISSUE TITLE
Crash: ConcurrentModificationException at vitalypanov.phototracker.utils.TrackUtils.getDistanceOpenStreetMarkers(TrackUtils.java:73)

### ISSUE THREAD

**Issue by panovvitalik** [panovvitalik/PhotoTracker#143]
07-12 15:17:06.353 11132 11132 E AndroidRuntime: FATAL EXCEPTION: main
07-12 15:17:06.353 11132 11132 E AndroidRuntime: Process: vitalypanov.phototracker, PID: 11132
07-12 15:17:06.353 11132 11132 E AndroidRuntime: java.util.ConcurrentModificationException
07-12 15:17:06.353 11132 11132 E AndroidRuntime: 	at java.util.ArrayList$Itr.next(ArrayList.java:860)
07-12 15:17:06.353 11132 11132 E AndroidRuntime: 	at vitalypanov.phototracker.utils.TrackUtils.getDistanceOpenStreetMarkers(TrackUtils.java:73)
07-12 15:17:06.353 11132 11132 E AndroidRuntime: 	at vitalypanov.phototracker.utils.MapOpenStreetUtils.addTrackData(MapOpenStreetUtils.java:143)
07-12 15:17:06.353 11132 11132 E AndroidRuntime: 	at vitalypanov.phototracker.fragment.MapOpenStreetSupportFragment.updateTrackDataUI(MapOpenStreetSupportFragment.java:317)
07-12 15:17:06.353 11132 11132 E AndroidRuntime: 	at vitalypanov.phototracker.fragment.MapOpenStreetSupportFragment.access$000(MapOpenStreetSupportFragment.java:69)
07-12 15:17:06.353 11132 11132 E AndroidRuntime: 	at vitalypanov.phototracker.fragment.MapOpenStreetSupportFragment$1.onTaskCompleted(MapOpenStreetSupportFragment.java:141)
07-12 15:17:06.353 11132 11132 E AndroidRuntime: 	at vitalypanov.phototracker.utils.AssyncBitmapLoaderTask.onPostExecute(AssyncBitmapLoaderTask.java:74)
07-12 15:17:06.353 11132 11132 E AndroidRuntime: 	at vitalypanov.phototracker.utils.AssyncBitmapLoaderTask.onPostExecute(AssyncBitmapLoaderTask.java:19)
07-12 15:17:06.353 11132 11132 E AndroidRuntime: 	at android.os.AsyncTask.finish(AsyncTask.java:695)
07-12 15:17:06.353 11132 11132 E AndroidRuntime: 	at android.os.AsyncTask.-wrap1(Unknown Source:0)
07-12 15:17:06.353 11132 11132 E AndroidRuntime: 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
07-12 15:17:06.353 11132 11132 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
07-12 15:17:06.353 11132 11132 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:169)
07-12 15:17:06.353 11132 11132 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6595)
07-12 15:17:06.353 11132 11132 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-12 15:17:06.353 11132 11132 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
07-12 15:17:06.353 11132 11132 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by panovvitalik** [comment]
Fixed
