### ISSUE TITLE
Flickr - remove from log errors which are regarding to get photos.

### ISSUE THREAD

**Issue by panovvitalik** [panovvitalik/PhotoTracker#144]
Exception example which should be removed: 
07-12 15:17:18.694  6065  6092 E FlickFetcher: Unable to resolve host "api.flickr.com": No address associated with hostname
07-12 15:17:18.694  6065  6092 E FlickFetcher: 	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:111)
07-12 15:17:18.694  6065  6092 E FlickFetcher: 	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:90)
07-12 15:17:18.694  6065  6092 E FlickFetcher: 	at java.net.InetAddress.getAllByName(InetAddress.java:787)
07-12 15:17:18.694  6065  6092 E FlickFetcher: 	at com.android.okhttp.Dns$1.lookup(Dns.java:39)
07-12 15:17:18.694  6065  6092 E FlickFetcher: 	at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:175)
07-12 15:17:18.694  6065  6092 E FlickFetcher: 	at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:141)
07-12 15:17:18.694  6065  6092 E FlickFetcher: 	at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:83)
07-12 15:17:18.694  6065  6092 E FlickFetcher: 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:174)
07-12 15:17:18.694  6065  6092 E FlickFetcher: 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
07-12 15:17:18.694  6065  6092 E FlickFetcher: 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
07-12 15:17:18.694  6065  6092 E FlickFetcher: 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
07-12 15:17:18.694  6065  6092 E FlickFetcher: 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
07-12 15:17:18.694  6065  6092 E FlickFetcher: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
07-12 15:17:18.694  6065  6092 E FlickFetcher: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
07-12 15:17:18.694  6065  6092 E FlickFetcher: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:244)
07-12 15:17:18.694  6065  6092 E FlickFetcher: 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
07-12 15:17:18.694  6065  6092 E FlickFetcher: 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(null:0)
07-12 15:17:18.694  6065  6092 E FlickFetcher: 	at vitalypanov.phototracker.flickr.Flickr.getUrlBytes(Flickr.java:560)
07-12 15:17:18.694  6065  6092 E FlickFetcher: 	at vitalypanov.phototracker.flickr.Flickr.getUrlString(Flickr.java:589)
07-12 15:17:18.694  6065  6092 E FlickFetcher: 	at vitalypanov.phototracker.flickr.Flickr.searchPhotos(Flickr.java:125)
07-12 15:17:18.694  6065  6092 E FlickFetcher: 	at vitalypanov.phototracker.flickr.FlickrSearchTask.doInBackground(FlickrSearchTask.java:37)
07-12 15:17:18.694  6065  6092 E FlickFetcher: 	at vitalypanov.phototracker.flickr.FlickrSearchTask.doInBackground(FlickrSearchTask.java:16)
07-12 15:17:18.694  6065  6092 E FlickFetcher: 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
07-12 15:17:18.694  6065  6092 E FlickFetcher: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
07-12 15:17:18.694  6065  6092 E FlickFetcher: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
07-12 15:17:18.694  6065  6092 E FlickFetcher: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
07-12 15:17:18.694  6065  6092 E FlickFetcher: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
07-12 15:17:18.694  6065  6092 E FlickFetcher: 	at java.lang.Thread.run(Thread.java:764)
07-12 15:17:18.694  6065  6092 E FlickFetcher: 
07-12 15:17:18.695  6065  6092 E FlickFetcher: Failed to parse JSON org.json.JSONException: End of input at character 0 of

**Comment by panovvitalik** [comment]
07-12 15:17:18.694  6065  6092 E FlickFetcher: Unable to resolve host "api.flickr.com": No address associated with hostname
07-12 15:17:18.694  6065  6092 E FlickFetcher: 	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:111)
07-12 15:17:18.694  6065  6092 E FlickFetcher: 	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:90)
07-12 15:17:18.694  6065  6092 E FlickFetcher: 	at java.net.InetAddress.getAllByName(InetAddress.java:787)
07-12 15:17:18.694  6065  6092 E FlickFetcher: 	at com.android.okhttp.Dns$1.lookup(Dns.java:39)
07-12 15:17:18.694  6065  6092 E FlickFetcher: 	at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:175)
07-12 15:17:18.694  6065  6092 E FlickFetcher: 	at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:141)
07-12 15:17:18.694  6065  6092 E FlickFetcher: 	at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:83)
07-12 15:17:18.694  6065  6092 E FlickFetcher: 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:174)
07-12 15:17:18.694  6065  6092 E FlickFetcher: 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
07-12 15:17:18.694  6065  6092 E FlickFetcher: 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
07-12 15:17:18.694  6065  6092 E FlickFetcher: 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
07-12 15:17:18.694  6065  6092 E FlickFetcher: 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
07-12 15:17:18.694  6065  6092 E FlickFetcher: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
07-12 15:17:18.694  6065  6092 E FlickFetcher: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
07-12 15:17:18.694  6065  6092 E FlickFetcher: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:244)
07-12 15:17:18.694  6065  6092 E FlickFetcher: 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
07-12 15:17:18.694  6065  6092 E FlickFetcher: 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(null:0)
07-12 15:17:18.694  6065  6092 E FlickFetcher: 	at vitalypanov.phototracker.flickr.Flickr.getUrlBytes(Flickr.java:560)
07-12 15:17:18.694  6065  6092 E FlickFetcher: 	at vitalypanov.phototracker.flickr.Flickr.getUrlString(Flickr.java:589)
07-12 15:17:18.694  6065  6092 E FlickFetcher: 	at vitalypanov.phototracker.flickr.Flickr.searchPhotos(Flickr.java:125)
07-12 15:17:18.694  6065  6092 E FlickFetcher: 	at vitalypanov.phototracker.flickr.FlickrSearchTask.doInBackground(FlickrSearchTask.java:37)
07-12 15:17:18.694  6065  6092 E FlickFetcher: 	at vitalypanov.phototracker.flickr.FlickrSearchTask.doInBackground(FlickrSearchTask.java:16)
07-12 15:17:18.694  6065  6092 E FlickFetcher: 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
07-12 15:17:18.694  6065  6092 E FlickFetcher: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
07-12 15:17:18.694  6065  6092 E FlickFetcher: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
07-12 15:17:18.694  6065  6092 E FlickFetcher: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
07-12 15:17:18.694  6065  6092 E FlickFetcher: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
07-12 15:17:18.694  6065  6092 E FlickFetcher: 	at java.lang.Thread.run(Thread.java:764)
07-12 15:17:18.694  6065  6092 E FlickFetcher: 
07-12 15:17:18.695  6065  6092 E FlickFetcher: Failed to parse JSON org.json.JSONException: End of input at character 0 of

**Comment by panovvitalik** [comment]
Done
