### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method 'vitalypanov.phototracker.model.Track vitalypanov.phototracker.TrackerGPSService.getCurrentTrack()' on a null object reference 07-14 10:55:04.534 26456 26456 E AndroidRuntime: 	at vitalypanov.phototracker.fragment.RunningTrackShortInfoFragment$3.onClick(RunningTrackShortInfoFragment.java:186)

### ISSUE THREAD

**Issue by panovvitalik** [panovvitalik/PhotoTracker#148]

**Comment by panovvitalik** [comment]
--------- beginning of crash
07-14 10:55:04.534 26456 26456 E AndroidRuntime: FATAL EXCEPTION: main
07-14 10:55:04.534 26456 26456 E AndroidRuntime: Process: vitalypanov.phototracker, PID: 26456
07-14 10:55:04.534 26456 26456 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'vitalypanov.phototracker.model.Track vitalypanov.phototracker.TrackerGPSService.getCurrentTrack()' on a null object reference
07-14 10:55:04.534 26456 26456 E AndroidRuntime: 	at vitalypanov.phototracker.fragment.RunningTrackShortInfoFragment$3.onClick(RunningTrackShortInfoFragment.java:186)
07-14 10:55:04.534 26456 26456 E AndroidRuntime: 	at android.view.View.performClick(View.java:6274)
07-14 10:55:04.534 26456 26456 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:24729)
07-14 10:55:04.534 26456 26456 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:789)
07-14 10:55:04.534 26456 26456 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:98)
07-14 10:55:04.534 26456 26456 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:169)
07-14 10:55:04.534 26456 26456 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6595)
07-14 10:55:04.534 26456 26456 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-14 10:55:04.534 26456 26456 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
07-14 10:55:04.534 26456 26456 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
07-14 10:55:15.353 27296 27296 I zygote64: Late-enabling -Xcheck:jni
07-14 10:55:15.580 27296 27296 V Monotype: SetAppTypeFace- try to flip, app = vitalypanov.phototracker
07-14 10:55:15.585 27296 27296 V Monotype:     Typeface getFontPathFlipFont - systemFont = default#default
07-14 10:55:15.593 27296 27301 I zygote64: Do partial code cache collection, code=30KB, data=21KB
07-14 10:55:15.593 27296 27301 I zygote64: After code cache collection, code=30KB, data=21KB
07-14 10:55:15.593 27296 27301 I zygote64: Increasing code cache capacity to 128KB
07-14 10:55:15.636 27296 27296 V Monotype: SetAppTypeFace- try to flip, app = vitalypanov.phototracker
07-14 10:55:15.636 27296 27296 V Monotype:     Typeface getFontPathFlipFont - systemFont = default#default
07-14 10:55:15.987 27296 27296 D StorageUtils: /proc/mounts
07-14 10:55:15.987 27296 27296 D StorageUtils: rootfs / rootfs

**Comment by panovvitalik** [comment]
Fixed
