### ISSUE TITLE
Crashed. After taking about 20-30 photo pictures

### ISSUE THREAD

**Issue by panovvitalik** [panovvitalik/PhotoTracker#16]
FATAL EXCEPTION: AsyncTask #9
                                                                          Process: vitalypanov.phototracker, PID: 14899
                                                                          java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                              at android.os.AsyncTask$3.done(AsyncTask.java:318)
                                                                              at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                              at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                              at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                              at java.lang.Thread.run(Thread.java:761)
                                                                           Caused by: java.lang.NullPointerException
                                                                              at java.io.File.<init>(File.java:340)
                                                                              at vitalypanov.phototracker.utilities.FileUtils.getPhotoFile(FileUtils.java:43)
                                                                              at vitalypanov.phototracker.RunningTrackShortInfoFragment$AssyncUpdatePhotoAfterTakePhotoTask.doInBackground(RunningTrackShortInfoFragment.java:311)
                                                                              at vitalypanov.phototracker.RunningTrackShortInfoFragment$AssyncUpdatePhotoAfterTakePhotoTask.doInBackground(RunningTrackShortInfoFragment.java:282)
                                                                              at android.os.AsyncTask$2.call(AsyncTask.java:304)
                                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                              at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                              at java.lang.Thread.run(Thread.java:761)

**Comment by panovvitalik** [comment]
Fixed.
