### ISSUE TITLE
NullPointerException: OtherTracksSearchTask.java:65

### ISSUE THREAD

**Issue by panovvitalik** [panovvitalik/PhotoTracker#164]
08-21 08:44:15.770 26871 26926 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #4
08-21 08:44:15.770 26871 26926 E AndroidRuntime: Process: vitalypanov.phototracker, PID: 26871
08-21 08:44:15.770 26871 26926 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
08-21 08:44:15.770 26871 26926 E AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:353)
08-21 08:44:15.770 26871 26926 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
08-21 08:44:15.770 26871 26926 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
08-21 08:44:15.770 26871 26926 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
08-21 08:44:15.770 26871 26926 E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
08-21 08:44:15.770 26871 26926 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
08-21 08:44:15.770 26871 26926 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
08-21 08:44:15.770 26871 26926 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
08-21 08:44:15.770 26871 26926 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object[] java.util.Collection.toArray()' on a null object reference
08-21 08:44:15.770 26871 26926 E AndroidRuntime: 	at java.util.ArrayList.addAll(ArrayList.java:588)
08-21 08:44:15.770 26871 26926 E AndroidRuntime: 	at vitalypanov.phototracker.others.OtherTracksSearchTask.doInBackground(OtherTracksSearchTask.java:65)
08-21 08:44:15.770 26871 26926 E AndroidRuntime: 	at vitalypanov.phototracker.others.OtherTracksSearchTask.doInBackground(OtherTracksSearchTask.java:26)
08-21 08:44:15.770 26871 26926 E AndroidRuntime: 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
08-21 08:44:15.770 26871 26926 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
08-21 08:44:15.770 26871 26926 E AndroidRuntime: 	... 4 more

**Comment by panovvitalik** [comment]
Fixed
