### ISSUE TITLE
Exception when continue recording

### ISSUE THREAD

**Issue by panovvitalik** [panovvitalik/PhotoTracker#218]
FATAL EXCEPTION: main
                  Process: vitalypanov.phototracker, PID: 16898
                  java.lang.NullPointerException: Attempt to invoke virtual method 'double vitalypanov.phototracker.model.TrackLocation.getLatitude()' on a null object reference
                      at vitalypanov.phototracker.utils.MapOpenStreetUtils.addTrackPhotos(MapOpenStreetUtils.java:486)
                      at vitalypanov.phototracker.fragment.MapOpenStreetSupportFragment.updateTrackDataUI(MapOpenStreetSupportFragment.java:347)
                      at vitalypanov.phototracker.fragment.MapOpenStreetSupportFragment.access$000(MapOpenStreetSupportFragment.java:74)
                      at vitalypanov.phototracker.fragment.MapOpenStreetSupportFragment$1.onTaskCompleted(MapOpenStreetSupportFragment.java:151)
                      at vitalypanov.phototracker.utils.AssyncBitmapLoaderTask.onPostExecute(AssyncBitmapLoaderTask.java:74)
                      at vitalypanov.phototracker.utils.AssyncBitmapLoaderTask.onPostExecute(AssyncBitmapLoaderTask.java:19)
                      at android.os.AsyncTask.finish(AsyncTask.java:667)
                      at android.os.AsyncTask.-wrap1(AsyncTask.java)
                      at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6119)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by panovvitalik** [comment]
Fixed
