### ISSUE TITLE
Crash when recording the track

### ISSUE THREAD

**Issue by panovvitalik** [panovvitalik/PhotoTracker#236]
--------- beginning of crash
10-30 17:04:40.253 32390 32390 E AndroidRuntime: FATAL EXCEPTION: main
10-30 17:04:40.253 32390 32390 E AndroidRuntime: Process: vitalypanov.phototracker, PID: 32390
10-30 17:04:40.253 32390 32390 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getString(int)' on a null object reference
10-30 17:04:40.253 32390 32390 E AndroidRuntime: 	at vitalypanov.phototracker.utils.MetricsUtils.getStringMetrics(MetricsUtils.java:17)
10-30 17:04:40.253 32390 32390 E AndroidRuntime: 	at vitalypanov.phototracker.fragment.RunningTrackShortInfoFragment$19.run(RunningTrackShortInfoFragment.java:684)
10-30 17:04:40.253 32390 32390 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:790)
10-30 17:04:40.253 32390 32390 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-30 17:04:40.253 32390 32390 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
10-30 17:04:40.253 32390 32390 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6501)
10-30 17:04:40.253 32390 32390 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-30 17:04:40.253 32390 32390 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
10-30 17:04:40.253 32390 32390 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by panovvitalik** [comment]
Fixed
