### ISSUE TITLE
Crash: IllegalStateException: Fragment StartScreenFragment{4d5c0d3} not attached to a context.

### ISSUE THREAD

**Issue by panovvitalik** [panovvitalik/PhotoTracker#255]
12-02 17:01:27.014 20205 20205 E AndroidRuntime: java.lang.IllegalStateException: Fragment StartScreenFragment{4d5c0d3} not attached to a context.
12-02 17:01:27.014 20205 20205 E AndroidRuntime: 	at android.support.v4.app.Fragment.requireContext(Fragment.java:696)
12-02 17:01:27.014 20205 20205 E AndroidRuntime: 	at android.support.v4.app.Fragment.getResources(Fragment.java:760)
12-02 17:01:27.014 20205 20205 E AndroidRuntime: 	at vitalypanov.phototracker.fragment.StartScreenFragment.checkNotEndedTrackAndUpdateUI(StartScreenFragment.java:1078)

**Comment by panovvitalik** [comment]
Fixed
