### ISSUE TITLE
Crash when reading the blob SQLiteException: unknown error (code 0): Native could not create new byte[]

### ISSUE THREAD

**Issue by panovvitalik** [panovvitalik/PhotoTracker#268]
--------- beginning of crash
12-08 19:29:51.388 10325 10325 E AndroidRuntime: FATAL EXCEPTION: main
12-08 19:29:51.388 10325 10325 E AndroidRuntime: Process: vitalypanov.phototracker, PID: 10325
12-08 19:29:51.388 10325 10325 E AndroidRuntime: android.database.sqlite.SQLiteException: unknown error (code 0): Native could not create new byte[]
12-08 19:29:51.388 10325 10325 E AndroidRuntime: 	at android.database.CursorWindow.nativeGetBlob(Native Method)
12-08 19:29:51.388 10325 10325 E AndroidRuntime: 	at android.database.CursorWindow.getBlob(CursorWindow.java:403)
12-08 19:29:51.388 10325 10325 E AndroidRuntime: 	at android.database.AbstractWindowedCursor.getBlob(AbstractWindowedCursor.java:45)
12-08 19:29:51.388 10325 10325 E AndroidRuntime: 	at android.database.CursorWrapper.getBlob(CursorWrapper.java:147)
12-08 19:29:51.388 10325 10325 E AndroidRuntime: 	at vitalypanov.phototracker.database.BlobCursorWrapper.getBlob(BlobCursorWrapper.java:21)
12-08 19:29:51.388 10325 10325 E AndroidRuntime: 	at vitalypanov.phototracker.database.BlobDbHelper.getBlob(BlobDbHelper.java:81)
12-08 19:29:51.388 10325 10325 E AndroidRuntime: 	at vitalypanov.phototracker.database.UserAvatarDbHelper.readAdditionalInfo(UserAvatarDbHelper.java:128)
12-08 19:29:51.388 10325 10325 E AndroidRuntime: 	at vitalypanov.phototracker.database.UserAvatarDbHelper.getUserAvatar(UserAvatarDbHelper.java:97)
12-08 19:29:51.388 10325 10325 E AndroidRuntime: 	at vitalypanov.phototracker.database.UserDbHelper.readAdditionalInfo(UserDbHelper.java:132)
12-08 19:29:51.388 10325 10325 E AndroidRuntime: 	at vitalypanov.phototracker.database.CommentDbHelper.getCommentsWithWhereClause(CommentDbHelper.java:101)

**Comment by panovvitalik** [comment]
Fixed
