### ISSUE TITLE
Google Photos not working in release. But working in debug

### ISSUE THREAD

**Issue by panovvitalik** [panovvitalik/PhotoTracker#291]
Failed uploading photo to Google Photos.
Error cause:
java.lang.NoSuchMethodError: No static method join(Ljava/lang/CharSequence;Ljava/lang/Iterable;)Ljava/lang/String; in class Ljava/lang/String; or its super classes (declaration of 'java.lang.String' appears in /system/framework/core-oj.jar)
java.lang.NoSuchMethodError: No static method join(Ljava/lang/CharSequence;Ljava/lang/Iterable;)Ljava/lang/String; in class Ljava/lang/String; or its super classes (declaration of 'java.lang.String' appears in /system/framework/core-oj.jar)
Resume url: Optional.empty
java.lang.Exception: Error cause:
java.lang.NoSuchMethodError: No static method join(Ljava/lang/CharSequence;Ljava/lang/Iterable;)Ljava/lang/String; in class Ljava/lang/String; or its super classes (declaration of 'java.lang.String' appears in /system/framework/core-oj.jar)
java.lang.NoSuchMethodError: No static method join(Ljava/lang/CharSequence;Ljava/lang/Iterable;)Ljava/lang/String; in class Ljava/lang/String; or its super classes (declaration of 'java.lang.String' appears in /system/framework/core-oj.jar)
Resume url: Optional.empty
	at vitalypanov.phototracker.googlephotos.GooglePhotosAPIHelper.upload(GooglePhotosAPIHelper.java:175)
	at vitalypanov.phototracker.googlephotos.GooglePhotos.upload(GooglePhotos.java:309)
	at vitalypanov.phototracker.googlephotos.GooglePhotosUploadTask.doInBackground(GooglePhotosUploadTask.java:125)
	at vitalypanov.phototracker.googlephotos.GooglePhotosUploadTask.doInBackground(GooglePhotosUploadTask.java:21)
	at android.os.AsyncTask$2.call(AsyncTask.java:305)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:762)

**Comment by panovvitalik** [comment]
Cancleed. Due to this piece of shit library  was removed from project. All work doing with REST
