### ISSUE TITLE
Crash after like was set

### ISSUE THREAD

**Issue by panovvitalik** [panovvitalik/PhotoTracker#79]
![screenshot_20180510-094250](https://user-images.githubusercontent.com/29057366/39855969-c6716a84-5436-11e8-9e09-9af1d6b801a2.jpg)

**Comment by panovvitalik** [comment]
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
        at vitalypanov.phototracker.fragment.TrackListFragment$TrackListHolder$7$1$1.onTaskGetLikesCompleted(TrackListFragment.java:477)
        at vitalypanov.phototracker.backend.GetLikesTask.doInBackground(GetLikesTask.java:28)
        at vitalypanov.phototracker.backend.GetLikesTask.doInBackground(GetLikesTask.java:13)
        at android.os.AsyncTask$2.call(AsyncTask.java:295)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
        at java.lang.Thread.run(Thread.java:818)

**Comment by panovvitalik** [comment]
Fixed
